#!/bin/sh

# From http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
ZANATAJ_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

IVY_JAR=/usr/share/java/ivy.jar
if [ ! -r $IVY_JAR ]; then
  echo "Please install Apache Ivy to $IVY_JAR."
  echo "With Fedora or EPEL 6, run this as root: yum install apache-ivy"
  exit 1
fi


# Documentation for Ivy's command-line options are here:
# http://ant.apache.org/ivy/history/latest-milestone/standalone.html
# http://ant.apache.org/ivy/history/2.1.0/standalone.html


unset IVY_LOG_LEVEL IVY_REFRESH IVY_SETTINGS

# -error will omit ivy warnings
IVY_LOG_LEVEL=-error

# -refresh tells ivy to 'refresh dynamic resolved revisions' (eg SNAPSHOT deps)
IVY_REFRESH=-refresh

# override ivy resolvers
IVY_SETTINGS="-settings $ZANATAJ_HOME/ivysettings.xml"


LOGGING_OPTS="
  -Dorg.slf4j.simpleLogger.showDateTime=false
  -Dorg.slf4j.simpleLogger.showThreadName=false
  -Dorg.slf4j.simpleLogger.showLogName=false
  -Dorg.slf4j.simpleLogger.showShortLogName=false
  -Dorg.slf4j.simpleLogger.levelInBrackets=true
"

java \
  $LOGGING_OPTS \
  -jar $IVY_JAR \
  -ivy $ZANATAJ_HOME/ivy.xml \
  $IVY_LOG_LEVEL $IVY_REFRESH $IVY_SETTINGS \
  -main org.zanata.client.ZanataClient -args -- \
  "$@"
